#!/usr/bin/env bash
# Generate the N-participant fleet from deploy/.env:
#   docker-compose.gen.yml   caddy + code-server-1..N
#   Caddyfile.gen            uN. (IDE) + uN-app. (live React) per participant
#   users.txt                CSV handout: name,url,password
#
# Pure file generation — no Docker calls. Run via deploy/fleet.sh, or directly:
#   bash deploy/gen.sh [N]      (default N=10)
set -euo pipefail

N="${1:-10}"
HERE="$(cd "$(dirname "$0")" && pwd)"

# shellcheck disable=SC1091
set -a; . "$HERE/.env"; set +a
: "${DOMAIN:?DOMAIN missing in deploy/.env}"
: "${ACME_EMAIL:?ACME_EMAIL missing in deploy/.env}"

COMPOSE="$HERE/docker-compose.gen.yml"
CADDY="$HERE/Caddyfile.gen"
USERS="$HERE/users.txt"
SLOTS="$HERE/slots.json"

rand_pw() { openssl rand -base64 12 | tr -dc 'A-Za-z0-9' | cut -c1-10; }

# Preserve existing passwords across re-runs so the handout doesn't churn.
# Load any current users.txt into a name->password map BEFORE we overwrite it.
declare -A EXIST_PW
if [[ -f "$USERS" ]]; then
  while IFS=, read -r e_name e_url e_pw; do
    [[ "$e_name" == "name" || -z "$e_name" ]] && continue
    EXIST_PW["$e_name"]="$e_pw"
  done < "$USERS"
fi

# Load OpenRouter keys (one per line, # comments allowed) for distribution
# across containers. Fewer keys than participants -> round-robin reuse.
KEYS_FILE="$HERE/openrouter-keys.txt"
OR_KEYS=()
if [[ -f "$KEYS_FILE" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [[ -z "$line" || "${line:0:1}" == "#" ]] && continue
    OR_KEYS+=("$line")
  done < "$KEYS_FILE"
fi
NKEYS=${#OR_KEYS[@]}

# --- Caddyfile ---
{
  echo "# GENERATED by gen.sh — do not edit by hand. ${N} participants."
  echo "{"
  echo "	email ${ACME_EMAIL}"
  echo "}"
  echo
  echo "# Landing page: claim-your-spot at the bare domain."
  echo "${DOMAIN} {"
  echo "	reverse_proxy claim:8090"
  echo "}"
  echo
  echo "# Redirect www -> bare domain (people type www and would otherwise get a TLS error)."
  echo "www.${DOMAIN} {"
  echo "	redir https://${DOMAIN}{uri} permanent"
  echo "}"
  echo
  for i in $(seq 1 "$N"); do
    echo "u${i}.${DOMAIN} {"
    echo "	reverse_proxy code-server-${i}:8080"
    echo "}"
    echo "u${i}-app.${DOMAIN} {"
    echo "	reverse_proxy code-server-${i}:3000"
    echo "}"
    echo
  done
} > "$CADDY"

# --- compose header + caddy ---
{
  echo "# GENERATED by gen.sh — do not edit by hand. ${N} participants."
  echo "services:"
  echo "  caddy:"
  echo "    image: caddy:2"
  echo "    restart: unless-stopped"
  echo "    ports:"
  echo '      - "80:80"'
  echo '      - "443:443"'
  echo "    volumes:"
  echo "      - ./Caddyfile.gen:/etc/caddy/Caddyfile:ro"
  echo "      - caddy_data:/data"
  echo "      - caddy_config:/config"
} > "$COMPOSE"

# --- one code-server per participant + users.txt + slots.json ---
echo "name,url,password" > "$USERS"
SLOT_ENTRIES=()
for i in $(seq 1 "$N"); do
  pw="${EXIST_PW[Participant ${i}]:-}"
  [[ -z "$pw" ]] && pw="$(rand_pw)"
  orkey=""
  (( NKEYS > 0 )) && orkey="${OR_KEYS[$(( (i-1) % NKEYS ))]}"
  {
    echo "  code-server-${i}:"
    echo "    image: workshop-workspace:latest"
    echo "    restart: unless-stopped"
    echo "    environment:"
    echo "      - PASSWORD=${pw}"
    echo "      - PARTICIPANT_NAME=Participant ${i}"
    echo "      - SLOT_ID=${i}"
    echo "      - APP_URL=https://u${i}-app.${DOMAIN}"
    echo "      - OPENROUTER_API_KEY=${orkey}"
    echo "      - LITELLM_BASE_URL=${LITELLM_BASE_URL:-}"
    echo "      - MODEL=${MODEL:-claude-opus-4-7}"
    echo "    expose:"
    echo '      - "8080"'
    echo '      - "3000"'
    echo "    mem_limit: 3g"
  } >> "$COMPOSE"
  echo "Participant ${i},https://u${i}.${DOMAIN},${pw}" >> "$USERS"
  SLOT_ENTRIES+=("{\"id\":${i},\"url\":\"https://u${i}.${DOMAIN}\",\"password\":\"${pw}\"}")
done

# slots.json — consumed by the claim service (passwords live here, server-side).
{ printf '[\n'; (IFS=$'\n'; printf '  %s' "${SLOT_ENTRIES[0]}"; for e in "${SLOT_ENTRIES[@]:1}"; do printf ',\n  %s' "$e"; done); printf '\n]\n'; } > "$SLOTS"

# --- claim landing-page service ---
{
  echo "  claim:"
  echo "    build: ./claim"
  echo "    restart: unless-stopped"
  echo "    environment:"
  echo "      - ADMIN_TOKEN=${CLAIM_ADMIN_TOKEN:-}"
  echo "    volumes:"
  echo "      - ./slots.json:/app/slots.json:ro"
  echo "      - claim_data:/data"
  echo "    expose:"
  echo '      - "8090"'
} >> "$COMPOSE"

{
  echo "volumes:"
  echo "  caddy_data:"
  echo "  caddy_config:"
  echo "  claim_data:"
} >> "$COMPOSE"

echo "Generated for ${N} participants:"
echo "  $COMPOSE"
echo "  $CADDY"
echo "  $USERS"
echo "  $SLOTS  (claim landing page: https://${DOMAIN})"
if (( NKEYS > 0 )); then
  echo "  OpenRouter keys: ${NKEYS} distributed across ${N} containers (round-robin)."
else
  echo "  OpenRouter keys: none found (create deploy/openrouter-keys.txt, one key per line)."
fi
