// Zero-dependency "claim your spot" service for the workshop landing page.
// Serves a page where participants claim one of the N workspaces by name and
// get back their IDE URL + password. Slot assignment is atomic (single Node
// process, no await between check and assign), so concurrent claims never
// collide. A cookie makes it refresh-safe.
import http from "node:http"
import crypto from "node:crypto"
import { readFileSync, existsSync, writeFileSync, mkdirSync } from "node:fs"

const PORT = process.env.PORT || 8090
const SLOTS_FILE = process.env.SLOTS_FILE || "/app/slots.json"
const DATA_DIR = process.env.DATA_DIR || "/data"
const CLAIMS_FILE = `${DATA_DIR}/claims.json`
const ADMIN_TOKEN = process.env.ADMIN_TOKEN || ""

// Slots: [{ id, url, password }] — generated by gen.sh from users.txt.
const SLOTS = JSON.parse(readFileSync(SLOTS_FILE, "utf8"))
const slotById = new Map(SLOTS.map((s) => [String(s.id), s]))

// claims: { [slotId]: { name, token, claimedAt } } — persisted across restarts.
let claims = {}
try {
  if (existsSync(CLAIMS_FILE)) claims = JSON.parse(readFileSync(CLAIMS_FILE, "utf8"))
} catch (e) {
  console.error("could not read claims:", e.message)
}
function persist() {
  try {
    mkdirSync(DATA_DIR, { recursive: true })
    writeFileSync(CLAIMS_FILE, JSON.stringify(claims, null, 2))
  } catch (e) {
    console.error("persist failed:", e.message)
  }
}

const slotOfToken = (t) => {
  if (!t) return null
  for (const [id, c] of Object.entries(claims)) if (c.token === t) return id
  return null
}
const freeSlots = () => SLOTS.filter((s) => !claims[String(s.id)])

function cookies(req) {
  const out = {}
  for (const part of (req.headers.cookie || "").split(";")) {
    const i = part.indexOf("=")
    if (i > 0) out[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1).trim())
  }
  return out
}
const send = (res, code, obj, headers = {}) => {
  res.writeHead(code, { "content-type": "application/json", ...headers })
  res.end(JSON.stringify(obj))
}
const readBody = (req) =>
  new Promise((r) => {
    let d = ""
    req.on("data", (c) => (d += c))
    req.on("end", () => r(d))
  })

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, "http://x")
  const myToken = cookies(req).claim_token

  if (req.method === "GET" && url.pathname === "/") {
    res.writeHead(200, { "content-type": "text/html; charset=utf-8" })
    res.end(PAGE)
    return
  }

  // Live state for the grid (+ the caller's own slot, with password, if claimed).
  if (req.method === "GET" && url.pathname === "/api/state") {
    const mineId = slotOfToken(myToken)
    const mine = mineId
      ? { id: Number(mineId), url: slotById.get(mineId).url, password: slotById.get(mineId).password, name: claims[mineId].name }
      : null
    const slots = SLOTS.map((s) => ({ id: s.id, name: claims[String(s.id)]?.name || null, mine: String(s.id) === mineId }))
    send(res, 200, { slots, total: SLOTS.length, taken: Object.keys(claims).length, mine })
    return
  }

  // Claim a spot. Optional { slot } picks a specific one; otherwise next free.
  if (req.method === "POST" && url.pathname === "/api/claim") {
    let data = {}
    try {
      data = JSON.parse((await readBody(req)) || "{}")
    } catch {}

    // Already claimed in this browser? Return the same spot (refresh-safe).
    const existing = slotOfToken(myToken)
    if (existing) {
      const s = slotById.get(existing)
      send(res, 200, { ok: true, slot: { id: Number(existing), url: s.url, password: s.password }, name: claims[existing].name })
      return
    }

    const name = String(data.name || "").trim().slice(0, 40)
    if (!name) return send(res, 400, { ok: false, reason: "name_required" })

    // --- atomic critical section: no await between check and assign ---
    let chosen = null
    if (data.slot != null) {
      const id = String(data.slot)
      if (!slotById.has(id)) return send(res, 400, { ok: false, reason: "bad_slot" })
      if (claims[id]) return send(res, 409, { ok: false, reason: "slot_taken" })
      chosen = id
    } else {
      const f = freeSlots()
      if (!f.length) return send(res, 409, { ok: false, reason: "full" })
      chosen = String(f[0].id)
    }
    const token = crypto.randomBytes(16).toString("hex")
    claims[chosen] = { name, token, claimedAt: new Date().toISOString() }
    // --- end critical section ---
    persist()

    const s = slotById.get(chosen)
    send(res, 200, { ok: true, slot: { id: Number(chosen), url: s.url, password: s.password }, name }, {
      "set-cookie": `claim_token=${token}; Path=/; Max-Age=86400; SameSite=Lax`,
    })
    return
  }

  // Release your own spot (e.g. claimed by accident) — frees it for others.
  // Only touches the claim service state; the workspace container is untouched.
  if (req.method === "POST" && url.pathname === "/api/unclaim") {
    const id = slotOfToken(myToken)
    if (id) {
      delete claims[id]
      persist()
    }
    send(res, 200, { ok: true }, { "set-cookie": "claim_token=; Path=/; Max-Age=0; SameSite=Lax" })
    return
  }

  // Organizer reset between sessions: POST /api/reset?token=ADMIN_TOKEN
  if (req.method === "POST" && url.pathname === "/api/reset") {
    if (!ADMIN_TOKEN || url.searchParams.get("token") !== ADMIN_TOKEN) return send(res, 403, { ok: false })
    claims = {}
    persist()
    return send(res, 200, { ok: true })
  }

  res.writeHead(404)
  res.end("not found")
})
server.listen(PORT, () => console.log(`claim service listening on :${PORT} (${SLOTS.length} slots)`))

const PAGE = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI Coding Workshop — claim your spot</title>
<style>
  :root{ --bg:#f4f5f7; --card:#fff; --border:#e3e6ea; --text:#1a1f29; --muted:#6b7280; --accent:#2f54eb; --free:#1f9d57; }
  *{box-sizing:border-box}
  body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--text);min-height:100vh;line-height:1.45}
  .wrap{max-width:680px;margin:0 auto;padding:48px 20px 64px}
  h1{font-size:1.55rem;font-weight:650;margin:0 0 24px;letter-spacing:-.01em}
  h2{font-size:1.2rem;font-weight:650;margin:0 0 16px}
  .card{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:24px;margin-bottom:20px}
  label{display:block;font-size:.85rem;color:var(--muted);margin-bottom:6px}
  input[type=text]{width:100%;padding:12px 14px;font-size:1rem;border-radius:8px;border:1px solid var(--border);background:#fff;color:var(--text);margin-bottom:14px}
  input[type=text]:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 3px rgba(47,84,235,.12)}
  button{font-size:1rem;font-weight:600;border:0;border-radius:8px;padding:12px 18px;cursor:pointer;background:var(--accent);color:#fff;width:100%}
  button:hover{filter:brightness(1.05)}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(108px,1fr));gap:8px;margin-top:4px}
  .tile{background:#f0f1f3;border:1px solid var(--border);border-radius:8px;padding:10px;text-align:center;font-size:.82rem;min-height:56px;display:flex;flex-direction:column;justify-content:center;gap:2px}
  .tile .n{font-weight:700;font-size:.92rem}
  .tile.free{background:#fff;border-color:var(--free);cursor:pointer}
  .tile.free:hover{background:#f3fbf6}
  .tile.free .label{color:var(--free);font-weight:600}
  .tile.mine{border-color:var(--accent);background:#eef1fe}
  .tile .who{color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .count{color:var(--muted);font-size:.9rem;margin:0 0 10px}
  .big-link{display:block;text-align:center;background:var(--accent);color:#fff;font-weight:650;font-size:1.05rem;padding:14px;border-radius:8px;text-decoration:none;margin:6px 0 18px}
  .big-link:hover{filter:brightness(1.05)}
  .pwrow{display:flex;gap:8px;align-items:center;background:#f0f1f3;border:1px solid var(--border);border-radius:8px;padding:10px 12px;margin-bottom:6px}
  .pw{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:1.15rem;letter-spacing:.5px;flex:1}
  .copy{width:auto;padding:9px 14px;background:#fff;color:var(--text);border:1px solid var(--border);font-size:.9rem;font-weight:500}
  .copy:hover{background:#f7f8f9;filter:none}
  .link-btn{width:auto;background:none;color:var(--muted);border:0;padding:14px 0 0;font-size:.85rem;font-weight:500;text-decoration:underline;cursor:pointer}
  .link-btn:hover{color:var(--text);filter:none}
  .step{color:var(--muted);font-size:.92rem;margin:2px 0 8px}
  .err{color:#c0392b;min-height:1.2em;margin:8px 0 0;font-size:.9rem}
</style></head>
<body><div class="wrap">
  <h1>AI Coding Workshop</h1>
  <div id="app"></div>
  <div class="card">
    <p class="count" id="count">Loading…</p>
    <div class="grid" id="grid"></div>
  </div>
</div>
<script>
const app=document.getElementById('app'), grid=document.getElementById('grid'), count=document.getElementById('count')
let state=null, mode=null
const esc=s=>(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))

async function load(){
  try{ state=await (await fetch('/api/state')).json() }catch{ return }
  // Only (re)build the form/card when the mode actually changes — NEVER on a
  // routine poll, or the user's half-typed name (and focus) would be wiped.
  const newMode = state.mine ? 'mine' : 'form'
  if(newMode!==mode){ mode=newMode; if(state.mine) renderMine(state.mine); else renderForm() }
  renderGrid()
}

function renderGrid(){
  count.textContent = (state.total - state.taken)+' of '+state.total+' computers free'
  grid.innerHTML = state.slots.map(s=>{
    if(s.mine) return '<div class="tile mine"><span class="n">#'+s.id+'</span><span class="who">You ('+esc(s.name)+')</span></div>'
    if(s.name) return '<div class="tile"><span class="n">#'+s.id+'</span><span class="who">'+esc(s.name)+'</span></div>'
    return '<div class="tile free" onclick="claim('+s.id+')"><span class="n">#'+s.id+'</span><span class="label">Claim →</span></div>'
  }).join('')
}

function renderForm(){
  app.innerHTML = '<div class="card">'
    + '<label for="name">Your name</label>'
    + '<input id="name" type="text" placeholder="e.g. Alex" autocomplete="off" maxlength="40">'
    + '<button id="go">Claim my spot</button>'
    + '<p class="err" id="err"></p></div>'
  const name=document.getElementById('name')
  name.focus()
  document.getElementById('go').onclick=()=>claim(null)
  name.addEventListener('keydown',e=>{ if(e.key==='Enter') claim(null) })
}

function renderMine(m){
  app.innerHTML = '<div class="card">'
    + '<h2>You\\'re in, '+esc(m.name)+'</h2>'
    + '<p class="step">1. Copy your password:</p>'
    + '<div class="pwrow"><span class="pw" id="pw">'+esc(m.password)+'</span>'
    + '<button class="copy" id="cp">Copy</button></div>'
    + '<p class="step">2. Open your workspace and paste it when asked:</p>'
    + '<a class="big-link" href="'+m.url+'" target="_blank" rel="noopener">Open my workspace</a>'
    + '<button class="link-btn" id="release">Not your spot? Release it</button>'
    + '</div>'
  document.getElementById('cp').onclick=async()=>{ try{await navigator.clipboard.writeText(m.password); document.getElementById('cp').textContent='Copied'}catch{} }
  document.getElementById('release').onclick=unclaim
}

async function claim(slot){
  const nameEl=document.getElementById('name')
  const name=nameEl?nameEl.value.trim():''
  const err=document.getElementById('err')
  if(!state.mine && !name){ if(err)err.textContent='Please enter your name first.'; if(nameEl)nameEl.focus(); return }
  const r=await fetch('/api/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,slot})})
  const d=await r.json()
  if(d.ok){ state.mine=d.slot; state.mine.name=d.name; await load(); }
  else if(err){ err.textContent = d.reason==='slot_taken'?'Just taken — pick another!':d.reason==='full'?'All spots are taken.':'Please enter your name.'; await load() }
  else { await load() }
}

async function unclaim(){
  if(!confirm('Release your spot? It will become available for someone else.')) return
  try{ await fetch('/api/unclaim',{method:'POST'}) }catch{}
  state.mine=null; mode='form'; renderForm(); load()
}

load(); setInterval(load, 3000)
</script>
</body></html>`
